### ISSUE TITLE
Deploy to PyPI with GitHub actions

### ISSUE THREAD

**Issue by mrwilson** [mrwilson/adr-viewer#15]
Merging a PR should build the library and publish to PyPI

**Comment by alshapton** [comment]
I can do this, but there seems to be Travis remnants around - do we still use Travis, or is there a move to Github Actions ?

I can create the deployment scripts, and would recommend a release/feature strategy for branching. I can document this for your acceptance before I implement, and this could form the basis of a CONTRIBUTIONS.md document.

Are you happy @mrwilson for me to start on this ?

**Comment by mrwilson** [comment]
Yep, Travis can be binned - I've previously deployed this manually but I'm sure there's a good way of publishing to PyPI with GHA.

**Comment by alshapton** [comment]
There is. I'll use my credentials for now, but will switch to yours when I
am sure it works.
