### ISSUE TITLE
Support Mermaid diagrams

### ISSUE THREAD

**Issue by colindean** [mrwilson/adr-viewer#36]
My team's enjoying GitHub's support for [Mermaid diagrams](https://www.mermaidchart.com) when writing and viewing our ADRs in GitHub instead of needing a CI pipeline for PlantUML diagrams. However, when we use adr-viewer, its output leaves the Mermaid diagrams as pre-formatted text. It'd be lovely to have an option to enable embedding the code necessary to enable Mermaid, or autodetect and include it.

**Comment by mrwilson** [comment]
I'd be very onboard with this feature, mermaid is great and I use it myself for work ADRs.

A quick scan doesn't seem to reveal a python implementation of the mermaid library, so this would probably need to depend on the JS `mermaid-cli` under the bonnet.

**Comment by josephm28** [comment]
Hi @mrwilson and @colindean! I was just thinking how nice it would be to have this and then saw this got added with https://github.com/mrwilson/adr-viewer/pull/45 in [v1.4.0](https://github.com/mrwilson/adr-viewer/releases/tag/1.4.0). 

However, after upgrading to 1.4.0, Mermaid diagrams still do not get processed/displayed. I checked the DOM and don't see the Mermaid script. My diagrams are added as
![image](https://github.com/mrwilson/adr-viewer/assets/3217515/eeeaf3f7-2654-4660-a29a-609e900c24ec)

Any suggestions?

**Comment by mrwilson** [comment]
@josephm28 I've just published [1.5.0-RC1](https://pypi.org/project/adr-viewer/1.5.0rc1/) with what I hope is the right fix, are you able to confirm it addresses the issue?

**Comment by josephm28** [comment]
Thanks for taking a look! Yes, it works now.
