### ISSUE TITLE
How do I set the project name?

### ISSUE THREAD

**Issue by chrkaatz** [mrwilson/adr-viewer#4]
I am unable to find out how I can set the project name during the creation of the output.

**Comment by mrwilson** [comment]
Hi Christian,

Apologies for delay in replying.

Project name is, by default, the name of the project's working directory. See [the source](https://github.com/mrwilson/adr-viewer/blob/master/adr_viewer/__init__.py#L80).

Is project name configurability a desired feature for you?

Cheers,

Alex

**Comment by chrkaatz** [comment]
That would be great - also sorry from my side for the delay
