### ISSUE TITLE
Links between ADRs don't resolve

### ISSUE THREAD

**Issue by tylerbrandt** [mrwilson/adr-viewer#8]
Just stumbled across this project while looking for a way to visualize a set of ADRs and at the same time allow looking at them in more detail. I really like the colored headers/icons for status which is really glanceable. 

However, I tend to use links (e.g. `adr new -l`) a lot, and since this project generates a single index.html for all ADRs, those (relative) links don't resolve. Using this project's ADRs as an example, while running `adr-viewer --serve`:

Clicking on the link to 3:
![Screen Shot 2020-09-17 at 12 52 25 AM](https://user-images.githubusercontent.com/1256483/93436900-3bbd8580-f880-11ea-9d61-1eb7c7cf0033.png)

Results in a 404 Not Found:
![Screen Shot 2020-09-17 at 12 52 29 AM](https://user-images.githubusercontent.com/1256483/93436939-4710b100-f880-11ea-8ae3-44bcf34a5250.png)

**Comment by gaggle** [comment]
@mrwilson any chance this can get merged into main? 🙏
